project:
  type: website

execute:
  freeze: auto

website:
  repo-url: https://github.com/kb-labb/easyaligner
  title: "easyaligner"
  navbar:
    background: dark
    search: true
    right:
      - text: "Get Started"
        href: get-started/overview.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/kb-labb/easyaligner
  sidebar:
    - id: get-started
      title: "Get Started"
      contents:
        - get-started/overview.qmd
  open-graph: 
    title: "easyaligner: Forced Alignment Made Easy"
    description: 
      "easyaligner is a fast and memory efficient forced alignment pipeline for speech and text.
      Given a text transcript, easyaligner will help identify where each word or phrase was spoken in the audio."
    image: _assets/easyaligner.png

# tell quarto to read the generated sidebar
metadata-files:
  - reference/_sidebar.yml

# tell quarto to read the generated styles
format:
  html:
    theme:
      dark:
        - cosmo
        - styles/dark-custom.scss
      light: 
        - cosmo
        - styles/light-custom.scss
    css:
      - reference/_styles-quartodoc.css
      - styles.css

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: easyaligner
  renderer:
    style: markdown
    table_style: table # description-list
  # write sidebar and style data
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Pipelines
      desc: 
        Pipelines and functions for forced alignment, emission extraction, and VAD. 
      package: easyaligner.pipelines
      contents:
        - pipeline
        - vad_pipeline
        - emissions_pipeline
        - alignment_pipeline
        - vad_pipeline_generator
        - emissions_pipeline_generator
        - alignment_pipeline_generator
    - title: Text Processing
      desc: 
        Text processing utilities. `from easyaligner.text.normalization import function_name`.
      package: easyaligner.text
      contents:
        - name: normalization.SpanMapNormalizer
          children: separate
        - normalization.text_normalizer
        - tokenizer.load_tokenizer
    - title: Datasets and I/O
      desc: 
        Dataset classes for creating Pytorch DataLoaders, and reading JSON/Msgpack metadata. 
        `from easyaligner.data.dataset import ClassName`
      package: easyaligner
      contents:
        - name: data.dataset.StreamingAudioFileDataset
          children: separate
        - name: data.dataset.AudioFileDataset
          children: separate
        - name: data.dataset.JSONMetadataDataset
          children: separate
        - name: data.dataset.MsgpackMetadataDataset
          children: separate
        - data.utils.read_json
    - title: Data Models
      desc: 
        Data models for storing transcribed text and metadata. 
        `from easyaligner.data.datamodel import ClassName`
      package: easyaligner.data.datamodel
      contents:
        - AudioMetadata
        - SpeechSegment
        - WordSegment
        - AlignmentSegment
        - AudioChunk
